### ISSUE TITLE
Display no events label below the month view on click of today button 

### ISSUE THREAD

**Issue by Ashab31** [mattlewis92/angular-calendar#503] opened 2018-04-17 07:00 UTC
## I'm submitting a ...

<pre>
[ ] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Versions

Angular: Angular 5

Calendar library: 

Browser name and version:  chrome

I want a feature to show no events label when I click on the TODAY button in the header. The no events label should be displayed below the MONTH view.

**Comment by etwillbefine** [comment] 2018-04-17 10:16
That can be easily achieved. You are passing an array of events into the view. Below the component you can add an additional check like this:

```
<mwl-calendar-month-view [viewDate]="viewDate" 
                         [events]="yourEventArray">
</mwl-calendar-month-view>

<div *ngIf="!yourEventArray.length">There are no events in this month</div>
```

Duplicate of https://github.com/mattlewis92/angular-calendar/issues/504

**Closed by etwillbefine** 2018-04-17 10:16 UTC
