### ISSUE TITLE
Can we have Tile view expand across the calendar in the month view like Google Calendar?

### ISSUE THREAD

**Issue by Kinjal10** [mattlewis92/angular-calendar#851] opened 2019-01-16 14:00 UTC
**Is your feature request related to a problem? Please describe**

**Describe the solution you'd like**

**Describe your use case for implementing this feature**

**Additional context**

**Comment by mattlewis92** [comment] 2019-02-03 04:42
Closing as a duplicate of https://github.com/mattlewis92/angular-calendar/issues/758

**Closed by mattlewis92** 2019-02-03 04:42 UTC
