### ISSUE TITLE
Draggable events on month view using custom template

### ISSUE THREAD

**Issue by einsuas** [mattlewis92/angular-calendar#705] opened 2018-09-03 15:40 UTC
**Describe the bug**

I there, amazing component, I have a problem, when I use a custom template the draggable property of the events no works, in the others view it actually works but in the month view its do not `work:`

```
`<context-menu #basicMenu>
  <template contextMenuItem [visible]="true" (execute)="addEvent($event.item)">
    Add session
  </template>
</context-menu>
<ng-template
   #monthCellTemplate let-day="day let-openDay="openDay"let-locale="locale"
   let-tooltipPlacement="tooltipPlacement" let-highlightDay="highlightDay" let- 
   unhighlightDay="unhighlightDay" let-eventClicked="eventClicked"
   let-eventTimesChanged = "eventTimesChanged">
<div class="fill-height" mwlDroppable [contextMenu]="basicMenu" [contextMenuSubject]="day.date">
  <div class="cal-cell-top">
  </div>
  <div class="cal-events">
    <div  class="cal-event"
      *ngFor="let event of day.events"
      [style.backgroundColor]="event.color.primary"
      [ngClass]="event?.cssClass"
      (mouseenter)="highlightDay.emit({event: event})"
      (mouseleave)="unhighlightDay.emit({event: event})"
      [mwlCalendarTooltip]="event.title | calendarEventTitle:'monthTooltip':event"
      [tooltipPlacement]="tooltipPlacement"
      (click)="$event.stopPropagation(); eventClicked.emit({event: event})">
    </div>
  </div>
</div>
</ng-template>
<div [ngSwitch]="view">
<mwl-calendar-month-view
  *ngSwitchCase="'month'"
  [viewDate]="viewDate"
  [events]="events"
  (dayClicked)=" setHours($event);"
  (eventClicked)="eventClicked($event)"
  [cellTemplate]="monthCellTemplate"
  [refresh]="refresh"
  (eventTimesChanged)="eventTimesChanged($event)">
</mwl-calendar-month-view>
<mwl-calendar-week-view
  *ngSwitchCase="'week'"
  [viewDate]="viewDate"
  [events]="events"
  (dayHeaderClicked)="setHours($event);"
  (eventClicked)="eventClicked($event)"
  [headerTemplate]="weekHeaderTemplate"
  [refresh]="refresh"
  (eventTimesChanged)="eventTimesChanged($event)">
</mwl-calendar-week-view>
<mwl-calendar-day-view
  *ngSwitchCase="'day'"
  [viewDate]="viewDate"
  [events]="events"
  [dayStartHour]="min_hour"
  [dayEndHour]="max_hour"
  [hourSegments]="4"
  (beforeViewRender)="setHours($event);"
  (eventClicked)="eventClicked($event)"
  [hourSegmentTemplate]="dayHourSegmentTemplate"
  [refresh]="refresh"
  (eventTimesChanged)="eventTimesChanged($event)">
</mwl-calendar-day-view>`
```

**Minimal reproduction of the problem with instructions**

**Versions**

- `@angular/core`: 4.0
- `angular-calendar`: 0.22.1
- Browser name and version: Chrome 68.0

**Comment by mattlewis92** [comment] 2018-09-03 20:58
Closing as dupe of https://github.com/mattlewis92/angular-calendar/issues/698 (see answer there)

**Closed by mattlewis92** 2018-09-03 20:58 UTC
