### ISSUE TITLE
export 'CalendarEvent' was not found in _____

### ISSUE THREAD

**Issue by JaxonWright** [mattlewis92/angular-calendar#1016] opened 2019-06-25 17:29 UTC
**Describe the bug**

I am including the CalendarEvent interface in multiple components. This error only occurs in one of them.

I have tried importing CalendarEvent from both _angular-calendar_ and _calendar-utils_ but get the same error.

The difference between this component and all of the others is that this is a Angular Material Dialog. The error is caused by using this interface on the data that is injected into the dialog as seen below.

````typescript
constructor(public dialogRef: MatDialogRef<EventDialogComponent>, 
             @Inject(MAT_DIALOG_DATA) public data: CalendarEvent) { 
...
}
````

I do know this had been working for a while and then suddenly stopped working today. 

Changing the type to _any_ gets around the issue, but then enables us to make possible errors down the road with no type set.

**Minimal reproduction of the problem with instructions**

I don't have one. Sorry

**Versions**

- `@angular/core`: 8.0.2
- `angular-calendar`: 0.27.11
- `typescript`: 3.4.5
- `Browser name and version:` Chrome 75.0.3770.100

**Comment by mattlewis92** [comment] 2019-06-25 21:40
I believe this is caused by https://github.com/angular/angular-cli/issues/14876 

If you pin the cli to the last known good working version then it should resolve the issue until the fix makes it's way live to npm:
```
npm i -D @angular-devkit/build-angular@0.800.1
```

**Comment by JaxonWright** [comment] 2019-06-25 22:46
@mattlewis92 that definitely appears to be the issue. Feel free to close this, then.

**Comment by mattlewis92** [comment] 2019-06-26 11:47
I'll leave it open for visibility for others until the cli gets updated with the fix 😄

**Comment by mattlewis92** [comment] 2019-06-28 12:00
`8.0.5` of the cli was just released with the fix: https://github.com/angular/angular-cli/releases/tag/v8.0.5 🎉

**Closed by mattlewis92** 2019-06-28 12:00 UTC
