### ISSUE TITLE
Drag event highlight string

### ISSUE THREAD

**Issue by al37350** [mattlewis92/angular-calendar#183] opened 2017-04-13 14:42 UTC
### Bug description :
Drag event highlight string with this version. However this isn't happend with the angular 1 version.
Angular 4 : 
![alt text](https://media.giphy.com/media/wJqeR3AZ7zjmE/giphy.gif "Angular 4 version")

Angular 1 :
![alt text](https://media.giphy.com/media/fejnPf4HuHV60/giphy.gif "Angular 1 version")

**Comment by mattlewis92** [comment] 2017-04-14 11:24
I can't reproduce this:
![apr-14-2017 12-21-41](https://cloud.githubusercontent.com/assets/6425649/25042056/f7667714-210c-11e7-9204-b3605c8a11e1.gif)

It's odd that it works for you on the ng1 version, as I use the exact same way of preventing the text getting highlighted by setting `pointer-events: none`.

What browser / OS are you using?

**Comment by al37350** [comment] 2017-04-14 12:35
The problem happen only on firefox (it's works on chrome and opera) with windows 7, Mac OS and ubuntu.

**Comment by mattlewis92** [comment] 2017-04-14 13:22
It seems to be only preset in firefox (yay browser quirks 😭). Should be fixed now in 0.13.5, thanks for reporting! 👍

**Closed** 2017-04-14 13:22 UTC
