### ISSUE TITLE
Angular 6 issue

### ISSUE THREAD

**Issue by nitinht1988** [mattlewis92/angular-calendar#525] opened 2018-05-09 04:32 UTC
## I'm submitting a ...

<pre>
[x ] Bug report 
[ ] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
I am getting below error:

```
_node_modules/angular-calendar/modules/day/calendar-day-view.component.d.ts(3,10): error TS2305: Module '"C:/xampp/htdocs/matngular-latest/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/angular-calendar/modules/day/calendar-day-view.component.d.ts(4,10): error TS2305: Module '"C:/xampp/htdocs/matngular-latest/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/angular-calendar/modules/month/calendar-month-view.component.d.ts(3,10): error TS2305: Module '"C:/xampp/htdocs/matngular-latest/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/angular-calendar/modules/month/calendar-month-view.component.d.ts(4,10): error TS2305: Module '"C:/xampp/htdocs/matngular-latest/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.
node_modules/angular-calendar/modules/week/calendar-week-view.component.d.ts(2,10): error TS2305: Module '"C:/xampp/htdocs/matngular-latest/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/angular-calendar/modules/week/calendar-week-view.component.d.ts(3,10): error TS2305: Module '"C:/xampp/htdocs/matngular-latest/node_modules/rxjs/Subscription"' has no exported member 'Subscription'._
```

### Versions

Angular: 6.0

Calendar library: ^0.24.0

Browser name and version: Chrome

**Comment by volser** [comment] 2018-05-09 05:51
dup https://github.com/mattlewis92/angular-calendar/issues/512

**Comment by mattlewis92** [comment] 2018-05-09 14:47
Closing as a dupe of #512

**Closed by mattlewis92** 2018-05-09 14:47 UTC

**Comment by SuperRoo123** [comment] 2018-11-27 05:39
Hi,
am also getting build error of no WeekViewEvent
` error TS2305: Module '"D:/Ionic4/devdacticCalendar/node_modules/calendar-utils/calendar-utils"' has no exported member 'WeekViewEvent'.`
also applies to:
WeekViewEventResize
WeekViewEventRow

"angular-calendar": "^0.26.4"
"@angular/core": "~7.0.0"

**Comment by akshilshah** [comment] 2018-11-30 08:32
Hi, 
I am facing the same error please help

ERROR in src\app\attendance\attendance.component.html(33,34): : Property 'locale' does not exist on type 'AttendanceComponent'.
src\app\attendance\attendance.component.html(29,76): : Property 'viewDateChange' does not exist on type 'AttendanceComponent'.
src\app\attendance\attendance.component.html(32,55): : Property 'viewDateChange' does not exist on type 'AttendanceComponent'.
src\app\attendance\attendance.component.html(35,72): : Property 'viewDateChange' does not exist on type 'AttendanceComponent'.
