### ISSUE TITLE
Cannot read property 'kind' of undefined` - Potential Memory Leak?

### ISSUE THREAD

**Issue by mwyld** [mattlewis92/angular-calendar#1268] opened 2020-05-29 09:45 UTC
**Describe the bug**

Hi Matt Lewis,

I seem to be getting the following issue when building my angular 7 application for production:

`ERROR in ./node_modules/angular-calendar/fesm5/angular-calendar.js Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js): TypeError: Cannot read property 'kind' of undefined`

I have tried the following:

upgraded to the latest version of angular-calendar from v`0.28.5` to v`0.28.15`
increased the memory allocation by using `node --max_old_space_size=8048 ./node_modules/@angular/cli/bin/ng build --prod`

Here are our details

We are using angular CLI version v`8.0.2`
node version v`10.1.6`

Full Error:

`ERROR in ./node_modules/angular-calendar/fesm5/angular-calendar.js Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js): TypeError: Cannot read property 'kind' of undefined at isAngularDecoratorMetadataExpression (c:\Workspace\XXX\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file .js:265:35) at checkNodeForDecorators (c:\Workspace\XXX\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21) at visitNodes (c:\WorkspaceXXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16144:30) at Object.forEachChild (c:\Workspace\XXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js: 16370:24) at checkNodeForDecorators (c:\Workspace\XXX\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31) at visitNode (c:\Workspace\XXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24) at Object.forEachChild (c:\Workspace\XXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js: 16265:21) at checkNodeForDecorators (c:\Workspace\XXX\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31) at visitNode (c:\Workspace\XXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24) at Object.forEachChild (c:\Workspace\XXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js: 16322:24) at checkNodeForDecorators (c:\Workspace\XXX\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31) at visitNode (c:\Workspace\XXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24) at Object.forEachChild (c:\Workspace\XXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js: 16333:24) at checkNodeForDecorators (c:\Workspace\XXX\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31) at visitNode (c:\Workspace\XXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16135:24) at Object.forEachChild (c:\Workspace\XXX\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js: 16229:21)`

**Minimal reproduction of the problem with instructions**

`ng build --prod` on the application `angular-calendar` is on

**Screenshots**

N/A

**Versions**

- `@angular/core`: 7.1.0
- `angular-calendar`: 0.28.15
- Browser name and version: N/A

**Comment by Nimzi-Git** [comment] 2020-05-29 10:30
Have same issue with module. I am continuously increasing the memory but is not the fix :(

**Comment by mattlewis92** [comment] 2020-05-29 11:16
Hey, sorry to hear you're having issues. It sounds like the problem is being caused because your angular version (v7) doesn't match your angular cli version (v8). Please can you either upgrade the framework from v7 to v8 or downgrade the cli to v7. If that doesn't work please can you provide a minimal runnable repro on github, as without that it's really hard to say what's going wrong. Thank you! 😄

**Comment by mwyld** [comment] 2020-05-29 12:20
Apologies, I forgot to mention that the CLI version was actually the version of on my build server. I was using CLI version 7.3.10 and I was still hitting the same issue.

I cannot share my current repo but I will create a seperate new one if this helps?

**Comment by mattlewis92** [comment] 2020-05-29 12:30
> I cannot share my current repo but I will create a seperate new one if this helps?

Yeah if you can just create a new minimal repro that shows your issue that would be awesome. Alternatively a quicker way might be to try installing every patch version of angular-calendar between `0.28.5` and `0.28.15` in your app and then find the exact version that breaks, that would tell me exactly which commit broke it and give me an idea of where to look. Thanks! 😄

**Comment by mwyld** [comment] 2020-05-29 17:09
So after further investigation it appears to be an issue between version 0.28.5 and 0.28.15.
After removing the ^ character it worked again

**Comment by mattlewis92** [comment] 2020-05-30 07:56
Thanks for putting together that repo, it really helped. I found the issue and a workaround, so this should be fixed now in `0.28.16` 😄

**Closed** 2020-05-30 07:58 UTC

**Comment by mwyld** [comment] 2020-06-01 13:04
Thanks Matt! thanks for the quick turnaround on this!
