### ISSUE TITLE
Scroll and zoom with fingers does not work on the calendar area

### ISSUE THREAD

**Issue by sylvain-fr** [mattlewis92/angular-calendar#896] opened 2019-02-21 17:08 UTC
**Describe the bug**
Scroll and zoom with fingers does not work on the calendar area

**Minimal reproduction of the problem with instructions**
I can't initiate a scroll if I start to touch the screen on the agenda zone. But I can continue a scroll if it has been initiated outside the agenda.
This is the same of the zoom in / zoom out feature with two fingers.

**Screenshots**

**Versions**

- `@angular/core`:Current online version
- `angular-calendar`:Current online version
- Browser name and version:
I'm testing the calendar on the online demo from py androïd phone.

**Comment by mattlewis92** [comment] 2019-02-24 20:06
This is caused by hammerjs adding some css to clickable elements, I'm not really sure if there's a way to solve it out the box though, please see my reply here for more info: https://github.com/mattlewis92/angular-calendar/issues/867#issuecomment-460022307

Closing this one as it's a dupe of the other issue

**Closed by mattlewis92** 2019-02-24 20:06 UTC
