### ISSUE TITLE
Angular 10.0

### ISSUE THREAD

**Issue by bjoern2610** [mattlewis92/angular-calendar#1288] opened 2020-06-25 10:26 UTC
**Describe the bug**

Hello together,

i update Angular 9 to Angular 10.

Now i get this error message. Somebody know what to do?

Greetings Björn

ERROR Error: Cannot instantiate cyclic dependency! DateAdapter
at throwCyclicDependencyError (core.js:5357)
at R3Injector.hydrate (core.js:11262)
at R3Injector.get (core.js:11088)
at NgModuleRef$1.get (core.js:23982)
at Object.get (core.js:22238)
at getOrCreateInjectable (core.js:3799)
at Module.ɵɵdirectiveInject (core.js:13770)
at NodeInjectorFactory.CalendarPreviousViewDirective_Factory [as factory] (angular-calendar.js:917)
at getNodeInjectable (core.js:3907)
at instantiateAllDirectives (core.js:8022)

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`: 10.0
- `angular-calendar`: latest
- Browser name and version: chrome

**Comment by ljunokas** [comment] 2020-06-25 13:48
I managed to do quick (ugly) fix until update comes:
at the end of the module: 

```
import * as tslib_1 from 'tslib'
import * as date_fns_2 from 'date-fns'

function adapterFactory() {
  return tslib_1.__assign(tslib_1.__assign({}),date_fns_2);
}
```
and in imports: 
```
imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    MatSelectModule,
    MatTooltipModule,
    CalendarModule.forRoot({ provide: DateAdapter, useFactory: adapterFactory }),
  ...
  ],
```

**Comment by mattlewis92** [comment] 2020-06-26 11:34
Hey there, sorry to hear you're having issues, the problem is a bug with the angular cli itself (https://github.com/angular/angular-cli/issues/17967) and there is a fix in the works. Unfortunately you'll have to wait until `10.0.1` of the angular cli is released (sometime next week probably). Closing as a dupe of https://github.com/mattlewis92/angular-calendar/issues/1288

**Closed by mattlewis92** 2020-06-26 11:34 UTC

**Comment by jasonkonopacki** [comment] 2020-07-01 00:05
@mattlewis92 I'm not seeing any improvements on this with angular cli 10.0.2 which includes the referenced pr - I'm still receiving the following error.
`Error: Cannot instantiate cyclic dependency! DateAdapter
    at throwCyclicDependencyError (core.js:5322)
    at R3Injector.hydrate (core.js:11222)
    at R3Injector.get (core.js:11048)
    at injectInjectorOnly (core.js:800)
    at Module.ɵɵinject (core.js:804)
    at Object.CalendarUtils_Factory [as factory] (keydown-enter.directive.ts:18)
    at R3Injector.hydrate (core.js:11226)
    at R3Injector.get (core.js:11048)
    at NgModuleRef$1.get (core.js:23933)
    at Object.get (core.js:22198)`

**Comment by mattlewis92** [comment] 2020-07-01 09:20
@jasonkonopacki there is no 10.0.2 version of the cli, it's still on 10.0.0: https://www.npmjs.com/package/@angular/cli

**Comment by jasonkonopacki** [comment] 2020-07-06 12:29
@mattlewis92 Thanks for the clarification - @angular/cli@10.0.1 fixed the issue. Thank you!
