### ISSUE TITLE
Turn multi day event dots into a single line

### ISSUE THREAD

**Issue by kyleabens** [mattlewis92/angular-calendar#1307] opened 2020-07-29 17:36 UTC
**Is your feature request related to a problem? Please describe**

It can be frustrating to see what events are spanning multiple days in the month view without having to hover over each dot.

**Describe the solution you'd like**

It would be nice if we had the ability to turn the dots into lines that span across multiple days in the month view (see example below).

<img width="1101" alt="Screen Shot 2020-07-29 at 1 35 52 PM" src="https://user-images.githubusercontent.com/25699262/88833574-72402380-d1a0-11ea-8fa7-0057a8a3aee2.png">

**Describe your use case for implementing this feature**

I would use this feature to convey multi day events similar to Google Calendar for my users.  Love the calendar so far I just thought this would be a nice enhancement.

**Comment by mattlewis92** [comment] 2020-09-12 20:07
This is absolutely something I want to do as part of the Pro version I'm slowly working on: https://github.com/mattlewis92/angular-calendar/issues/857 It's really tricky to get right though (esp with drag and drop and resizing) which is why it's not something I can do quickly. I'm hoping to get something out the door sometime at the start of next year. Thanks for your patience!

Closing this issue as it's a dupe of https://github.com/mattlewis92/angular-calendar/issues/758

**Closed by mattlewis92** 2020-09-12 20:07 UTC
