### ISSUE TITLE
Modifying month view days based on data

### ISSUE THREAD

**Issue by SecretGibbon** [mattlewis92/angular-calendar#161] opened 2017-03-20 22:51 UTC
Hello, i have tried for 2 days now but i cannot get to the solution.
Is it possible to modify days background depending on data pulled via promise?

i have:

```
ngOnInit(): void {
    this.bookingService.getBookingCalendar(this.from, this.to)
      .then(bookingCalendar =>
        this.calendarData = bookingCalendar
      );
}
```
which works fine. But then in addCssClass() im not able to get the data for 2 reasons
1) the addCssClass() function is called BEFORE the promise is fullfiled
2) in addCssClass() "this" is the CalendarMonthViewComponent and not my component so im not able to get to the this.calendarData field nevertheless

I'm really sorry if this is stupid question, I'm just starting with JS and Angular2, but I really need some help in this matter.

**Comment by mattlewis92** [comment] 2017-03-21 10:17
1/ You have a few options on how to solve this. You can either
* use [a resolve](https://blog.thoughtram.io/angular/2016/10/10/resolving-route-data-in-angular-2.html) to make sure the data is loaded when the component is created
* use *ngIf to only render the calendar once the data is loaded
* use the `[refresh]` input to tell the calendar to re-render once the async data is loaded. There is an example of how to do that on the kitchen sink demo

2/ You can work around this by not using a class method. It's a bit of a sucky API but I couldn't think of anything better sadly. So something like this:
```
@Component({})
class MyComponent {
  constructor() {
    this.addCssClass = () => {
      // this is now the component instance
    }
  }
}
```

Hope that helps! 😄

**Closed by mattlewis92** 2017-03-21 10:17 UTC

**Comment by mattlewis92** [comment] 2017-03-21 11:44
I've just added a new demo that might help a bit more 😄 https://mattlewis92.github.io/angular-calendar/#/refreshing-the-view

**Comment by enyachoke** [comment] 2017-03-22 09:07
@mattlewis92  This is fantastic I have tried it out on the plunker and its is what we needed. We need to deal with the small issue upgrading to angular 4 before we start using the feature but I believe it should just work. Thanks again.

**Comment by mattlewis92** [comment] 2017-03-22 09:08
In the end I landed on a solution that didn't require angular 4 so you can start using it today without any changes to your app 😄

**Comment by SecretGibbon** [comment] 2017-03-22 23:13
Hi again,
maybe i'm doing it all wrong but now i have:

```
  constructor(private gameBookingService: GameBookingService,
              private router: Router) {
    this.gameBookingService.getBookingCalendar(new Date(2017, 2, 1), new Date(2017, 2, 31))
      .then(bookingCalendar =>
        this.calendarData = bookingCalendar)
      .then(() =>
        this.addCssClass = (day: CalendarMonthViewDay): void => {
          const calendarDay = this.getCalendarDay(day);
          if (calendarDay) {
            switch (calendarDay.color) {
              case 0:
                day.backgroundColor = '#ccc';
                break;
              default:
                day.backgroundColor = '#ff1500';
            }
          }
        }
      )
      .then(() => this.refresh.next());
  };
```

but the calendar has no colors when it shows up for the first time. If click TODAY or previous/next it refreshes and colors are there. But i cannot get it going on the first run.
Same behaviour occurs even without the `.then(() => this.refresh.next())`. I have also tried `*ngIf` with same results. 

Can you help me a bit more please? :)
I'm really sorry for troubling you with such trivial matters :(

**Comment by mattlewis92** [comment] 2017-03-22 23:57
It might be because the backgroundColor property is used for when you mouse over events and the calendar will reset this state on a refresh. I'd recommend setting a cssClass property instead on the day and then have that class apply the styling with the background colour.

**Comment by SecretGibbon** [comment] 2017-03-23 08:11
Unfortunately that's not the case. I have tried changing class as well. I have put `console.log()` commands to addCssClass method and they write to console AFTER i click any header button.

weird is that when I tried adding
```
.then(() => console.log("test");
```
to the end of the then chain it is called upon calling constructor. So the data are retrieved and addCssClass is added. But it is called upon clicking header button.

My guess is that the addCssClass is called upon construction on the component, then the promise in constructor retrieves the data and after that new implementation of addCssClass is added. So it does not apply to the first run. I hoped that refresh would help about it but i guess it does not.

**Comment by mattlewis92** [comment] 2017-03-23 08:44
If you can reproduce it in a plunker then I'll have a go at fixing it 😀

**Comment by SecretGibbon** [comment] 2017-03-23 21:51
It took me a while but i got it reproduced in plunker:

http://embed.plnkr.co/T7nHz1IBuv0cbqnk49Lc/

Can you please take a look?

I have left inside the console output, notice what happens when you click previous/today/next button.
relevant code is in 
booking-calendar-sm.component.ts

Thank you!

**Comment by mattlewis92** [comment] 2017-03-23 22:44
Thanks for doing that, I will take a look first thing tomorrow 😀

**Comment by mattlewis92** [comment] 2017-03-24 10:15
Ah it's because you're creating the function dynamically. When you call refresh the first time, angular hasn't picked up that the input value to `[dayModifier]` has changed so the function never gets called. Calling refresh the first time triggers change detection to kick in hence why it works for subsequent renders. You can solve this by defining the function in your constructor and just checking if the data is loaded, like so: https://plnkr.co/edit/0wAGumABEcP4ACpRbMzL?p=preview
