### ISSUE TITLE
ng serve Compile Errors in angular-calendar/dist/

### ISSUE THREAD

**Issue by datglowtho** [mattlewis92/angular-calendar#228] opened 2017-06-01 14:09 UTC
### Bug description / Feature request:
Having followed README and used an <mwl-calendar-week-view> in the template for a pre-existing component, when running ng serve we see a lot of similar errors, of the form: 

`ERROR in /Users/username/project/frontend/node_modules/calendar-utils/dist/calendarUtils.d.ts (20,41): ‘,’ expected.

ERROR in /Users/username/project/frontend/node_modules/calendar-utils/dist/calendarUtils.d.ts (17,16): Generic type ‘CalendarEvent<MetaType, any>’ requires 2 type argument(s).

ERROR in /Users/username/project/frontend/node_modules/calendar-utils/dist/calendarUtils.d.ts (20,43): Type parameter name cannot be ‘any’`

We have no idea why this is happening, can anyone help? We're pretty new to Angular and are struggling to work out what could cause this. It's behaving like your code doesn't compile but of course it should.

### Versions

Angular: v4.2.0

Calendar library: angular-calendar v0.17.0

Browser name and version: Chrome v58.0.3029.110 (64-bit) (not that we get this far).

**Comment by etwillbefine** [comment] 2017-06-01 14:10
Duplicate of https://github.com/mattlewis92/angular-calendar/issues/221
Please see this issue for more details

**Closed by etwillbefine** 2017-06-01 14:10 UTC
