### ISSUE TITLE
Problem importing angular-calendar in component

### ISSUE THREAD

**Issue by Nayk0** [mattlewis92/angular-calendar#223] opened 2017-05-31 08:21 UTC
Hi,

I tried to import angular-calendar (using your readme) but I get the error

node_modules/angular-calendar/dist/esm/src/providers/calendarEventTitleFormatter.provider.d.ts (27,18): Generic type 'CalendarEvent<MetaType, any>' requires 2 type argument(s).

I'm using Wakanda Studio

EDIT: might be related to this ? https://github.com/mattlewis92/calendar-utils/commit/7821b04229302f6cfe074cf3c50865b2935a6cd7#diff-fdb1138e6fb46aad8352fc0cbfb32a0eR49

**Comment by mattlewis92** [comment] 2017-05-31 09:02
Dupe of https://github.com/mattlewis92/angular-calendar/issues/221 The fix is to upgrade typescript to 2.3.x or use 0.16.0. I will revert the change and cut a new release when I have some free time.

**Closed by mattlewis92** 2017-05-31 09:02 UTC
