### ISSUE TITLE
Active Day is Open only if it has events

### ISSUE THREAD

**Issue by dgadelha** [mattlewis92/angular-calendar#346] opened 2017-10-07 00:36 UTC
## I'm submitting a ...
<pre>
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
Set active day as open only if it has events.

Currently, it will open the events list without any events.

Also, if you set active day is open to false, it won't be clickable to open if it has events.

### Versions

Angular: 4.4.4

Calendar library: 0.21.2

Browser name and version: Mozilla Firefox 58.0a1

**Comment by mattlewis92** [comment] 2017-10-09 11:33
This is by design, as some people use custom templates to insert buttons on days that have no events. The business logic for opening / closing the active day is left entirely up to you to implement yourself, you can see an example of how to keep days with no events closed [here](https://github.com/mattlewis92/angular-calendar/blob/master/demos/demo-modules/kitchen-sink/component.ts#L114-L126).

**Closed by mattlewis92** 2017-10-09 11:33 UTC
