### ISSUE TITLE
displaying events in bars with its title, instead of dots

### ISSUE THREAD

**Issue by DuraisHub** [mattlewis92/angular-calendar#1075] opened 2019-08-30 01:11 UTC
when an event spans multiple days, users dont realize it until they inspect each entry, as the events are displayed as dots in monthly view. 

Instead of dot, it would be good to have a bar stretching till the end date of the event, bearing its name. 

when you are enrolled for a training or OOO events, those will be much visible, as soon as you open the calendar.  

**Additional context**

similar to the bar that is used in day view,  we want something in monthly view.
<img width="594" alt="Screen Shot 2019-08-29 at 9 28 34 PM" src="https://user-images.githubusercontent.com/18900033/63987074-c3cdc300-caa4-11e9-8e44-9eac29136122.png">

**Comment by mattlewis92** [comment] 2019-09-01 11:19
Duplicate of https://github.com/mattlewis92/angular-calendar/issues/758, I will get round to making a demo of it as soon as I can showing how to do it with the existing api.

**Closed by mattlewis92** 2019-09-01 11:19 UTC

**Comment by hassansw** [comment] 2020-01-31 12:27
is this done?

**Comment by bgvas** [comment] 2022-07-07 06:27
Yes. It is possible: 

<ng-template #customCellTemplate let-day="day">
    <div *ngIf="day.events">
      <p class="bg-primary" *ngFor="let event of day.events; let x = index" (click)="handleEvent('Clicked', day.events[x])">
        <span class="text-white p-2 small">{{event?.title}}</span>
      </p>
    </div>
</ng-template>
 <mwl-calendar-month-view
      *ngSwitchCase="CalendarView.Month"
      [viewDate]="viewDate"
      [events]="events"
      [refresh]="refresh"
      [locale]="'el'"
      [cellTemplate]="customCellTemplate"
      (eventTimesChanged)="eventTimesChanged($event)">
    </mwl-calendar-month-view>

**Comment by jschank** [comment] 2022-11-02 17:24
In that example of using a banner for the event test. You lose the Day number. Is there a way to have both?

**Comment by hefemk** [comment] 2023-01-31 10:37
> In that example of using a banner for the event test. You lose the Day number. Is there a way to have both?

Just add the `div.cal-cell-top`:

```html
<ng-template #customCellTemplate let-day="day">
    <div class="cal-cell-top">
        <span class="cal-day-number">{{ day.date | calendarDate:'monthViewDayNumber':locale }}</span>
    </div>
    <div *ngIf="day.events">
        <p class="bg-primary" *ngFor="let event of day.events; let x = index" (click)="handleEvent('Clicked', day.events[x])">
        <span class="text-white p-2 small">{{event?.title}}</span>
      </p>
    </div>
</ng-template>
```

**Comment by sshaik125** [comment] 2025-11-04 14:41
@mattlewis92 I am using angular-calendar 0.31. I am unable to show an event span continuously across multiple days. 

It is still showing each event on each date repeatedly.

is it solved ?
