### ISSUE TITLE
Want to display the list of all events for the particular month in the month view upon clicking a button

### ISSUE THREAD

**Issue by Ashab31** [mattlewis92/angular-calendar#513] opened 2018-04-22 14:43 UTC
Hi Mattlewis,
  I will be grateful if I can a get response regarding my query of displaying the list of events for a particular month upon clicking the button on the month view of calendar page. 
 thanks in advance.

**Comment by mattlewis92** [comment] 2018-05-13 10:00
Dupe of https://github.com/mattlewis92/angular-calendar/issues/510

**Closed by mattlewis92** 2018-05-13 10:00 UTC
