### ISSUE TITLE
List of events for a day is not changing after selecting another day

### ISSUE THREAD

**Issue by Dafnik** [mattlewis92/angular-calendar#959] opened 2019-04-24 17:53 UTC
**Describe the bug**
After clickling in the month view on another day, the list of all events on this day is not changed. Sometimes it changes (after a long pause) and sometimes it doesn't change at all. Please note that this bug isn't affecting the demo and in my example I simply copied the demo.

**Minimal reproduction of the problem with instructions**

- Copy the demo to a new project.
- Select the month view
- Click on another day

**Screenshots**
[Streamable link](https://streamable.com/rraiq)

**Versions**

- `@angular/core`: 7.2.14
- `angular-calendar`: 0.27.5
- Browser name and version: Chromium - 73.0.3683.86 and Firefox - 66.0.3

**Comment by mattlewis92** [comment] 2019-04-24 18:03
Hey, sorry to hear you're having issues, please can you attach a runnable stackblitz that reproduces your issue? Without it I can't really tell what's going on, thanks! 😄

**Comment by Dafnik** [comment] 2019-04-24 18:16
Here you go: [Stackblitz app](https://angular-d8wdl7.stackblitz.io)
And here you can edit everything: [Stackblitz edit mode](https://stackblitz.com/edit/angular-d8wdl7)

**Comment by mattlewis92** [comment] 2019-04-24 18:31
Wow, that's so weird, it's like change detection just isn't working. If I call `detectChanges` after the dayClicked output it fixes it (https://stackblitz.com/edit/angular-eveyex?file=src%2Fapp%2Fapp.component.ts), but that shouldn't be needed at all.

**Comment by Dafnik** [comment] 2019-04-24 18:48
Maybe it's a bug in Angular. Anyways thank you for the "dirty fix"! :)

**Comment by cosf87** [comment] 2019-04-25 07:49
I have this issue after upgrading from 0.27.2 to 0.27.3 version

**Comment by mattlewis92** [comment] 2019-04-25 08:27
Ahhhh, yes, it'll be the lazy click handlers. I'll see what I can do!

**Comment by mattlewis92** [comment] 2019-04-27 09:21
Fixed in `0.27.6`!

**Closed** 2019-04-27 09:22 UTC
Labels: bug

**Comment by Dafnik** [comment] 2019-04-29 15:38
I don't know if this belongs here, but if I'm adding an event to the events array after ngInit (Fetching data etc from a server) it's also don't updating the complete calendar view. With cdr.detectChanges() it's working.

**Comment by mattlewis92** [comment] 2019-04-29 15:51
@Dafnik - Can you make a repro?

**Comment by Dafnik** [comment] 2019-04-30 13:43
Sure, https://stackblitz.com/edit/angular-eveyex

**Comment by mattlewis92** [comment] 2019-04-30 15:54
Sorry I'm not sure I can see the issue, the stackblitz is the one from this comment: https://github.com/mattlewis92/angular-calendar/issues/959#issuecomment-486372876

**Comment by Dafnik** [comment] 2019-04-30 21:08
Sorry, I shared the wrong url. Here you have the new one, adding an event after three seconds. I hope you can see that the calendar view isn't updating until you click on it.
https://stackblitz.com/edit/angular-ildcfe

**Comment by mattlewis92** [comment] 2019-04-30 21:23
Oh I see the issue, it's because you're using `.push` which doesn't create a new array references so angular doesn't know anything changed. You need to do something which creates a new array reference like this:

```
this.events = [
   ...this.events,
   {
          start: addHours(startOfDay(new Date()), 2),
          end: new Date(),
          title: 'An event added after three seconds',
          color: colors.yellow,
          actions: this.actions,
          resizable: {
            beforeStart: true,
            afterEnd: true
          },
          draggable: true
        }
]
```

**Comment by Dafnik** [comment] 2019-05-01 14:06
Ohh, thank you!
